# Generated by Django 3.1 on 2020-08-22 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.TextField()),
                ('cash_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.IntegerField()),
                ('close_time', models.IntegerField()),
                ('book_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.bookstore')),
            ],
        ),
        migrations.CreateModel(
            name='BookInBookStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.book')),
                ('book_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.bookstore')),
            ],
        ),
    ]
