# Generated by Django 3.1 on 2020-08-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0002_bookinbookstore_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinbookstore',
            name='user',
        ),
        migrations.AddField(
            model_name='bookinbookstore',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='store_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
